### ISSUE TITLE
mapa spring 2

### ISSUE THREAD

**Issue by kevinMazarelloJOSE** [SistemasTecTlaxiaco/actividad-4-mapa-mental-kevinMazarelloJOSE#2]
[Lluvia de Ideas Mapa Mental Creativo Colorido .zip](https://github.com/user-attachments/files/17106969/Lluvia.de.Ideas.Mapa.Mental.Creativo.Colorido.zip)

**Comment by A-Lorely-Z** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:0/5
Calificación Final:15/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
